version: '3.3'

services:
  back-end:
    build:
      context: ./src
      dockerfile: Dockerfile.backend

    volumes:
      - ./core/media:/home/app/web/core/media
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx/local
      dockerfile: Dockerfile.proxy
    volumes:
      - ./src/core/static:/home/app/web/static
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - back-end
      - php-fpm

  front:
    build:
      context: ../Umbrella-Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: 'umbrella'
    networks:
      - app_network

  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./src/.env
    networks:
      - app_network


  php-fpm:
    build:
      context: ./bitrix/tilda_integration
      dockerfile: Dockerfile
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./bitrix/tilda_integration:/var/www/html
    networks:
      - app_network




volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge