version: '3.3'

services:
  back-end:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - ./src/core/db.sqlite3/:/home/app/core/db.sqlite3/
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.proxy
    volumes:
      - ./src/core/static:/home/app/web/static
      - ./src/core/media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - back-end

  front:
    build:
      context: ../umbrella
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: 'umbrella'

  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./src/.env

volumes:
  static_volume:
  media_volume:
  postgres_data:
