version: '3.3'

services:
  back-end:
    build:
      context: ./src
      dockerfile: Dockerfile.backend

    volumes:
      - ./core/media:/home/app/web/core/media
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/prod
      dockerfile: Dockerfile.prod.proxy
    volumes:
      - ./src/core/static:/home/app/web/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back-end

  front:
    build:
      context: ../Umbrella-Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: 'umbrella'

  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./src/.env

volumes:
  static_volume:
  media_volume:
  postgres_data:
