# Generated by Django 5.0.7 on 2024-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_founder_url_vacancy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Цитата'),
        ),
    ]
