# Generated by Django 5.0.7 on 2024-09-10 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeStartJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'До начала работы',
                'verbose_name_plural': 'До начала работ',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание процесса')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('position', models.CharField(max_length=120, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('before_start_job', models.ManyToManyField(related_name='tab_before_start_job', to='service.beforestartjob', verbose_name='До начала работы')),
                ('processes', models.ManyToManyField(related_name='tab_processes', to='service.process', verbose_name='Процессы')),
                ('sections', models.ManyToManyField(related_name='tab_sections', to='service.section', verbose_name='Секции')),
                ('team', models.ManyToManyField(related_name='tab_team', to='service.teammember', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Таб',
                'verbose_name_plural': 'Табы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('short_description_for_banner', models.CharField(help_text='Макс. символов: 90', max_length=90, verbose_name='Краткое описание для баннера главной страницы')),
                ('gif', models.FileField(help_text='Загрузите гифку для услуги. Допустимые форматы: .gif', upload_to='gifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'], message='Допустимые форматы: .gif')], verbose_name='Гифка')),
                ('tabs', models.ManyToManyField(related_name='service_tabs', to='service.tab', verbose_name='Табы')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
