# Generated by Django 5.0.7 on 2024-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description_for_banner',
            field=models.CharField(help_text='Макс. символов: 120', max_length=120, verbose_name='Краткое описание для баннера главной страницы'),
        ),
    ]
