# Generated by Django 5.0.7 on 2024-10-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_tab_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.PositiveIntegerField(default=12, verbose_name='Последовательность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=21, verbose_name='Последовательность'),
            preserve_default=False,
        ),
    ]
