# Generated by Django 5.0.7 on 2024-10-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_process_order_section_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['created_at'], 'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.RemoveField(
            model_name='process',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
    ]
