# Generated by Django 5.0.7 on 2024-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_gif_alter_service_tabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeStartJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'До начала работы',
                'verbose_name_plural': 'До начала работ',
            },
        ),
        migrations.RemoveField(
            model_name='tab',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='tab',
            name='before_start_job',
            field=models.ManyToManyField(related_name='tab_before_start_job', to='service.beforestartjob', verbose_name='До начала работы'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
