# Generated by Django 5.0.7 on 2024-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_beforestartjob_remove_tab_portfolios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
